import { useEffect, useMemo, useRef, useState } from "react";
import { Trash2, X } from "lucide-react";
import {
  DEFAULT_PARTICIPANT_LISTEN_MODE,
  type Conversation,
  type CreateIdentityRequest,
  type Identity,
  type LocalAgentProviderStatus,
  type Participant,
  type ReasoningEffort,
  type Room,
  type RuntimeProfile,
} from "@group-chat/shared";
import { roleDescriptionPresets, reasoningEffortOptions, reasoningModeFieldLabel, defaultRoleDescription } from "../../constants.js";
import { getIdentityRoleDescription } from "../../identity-role.js";
import { resolveAgentAvatar } from "../../identity-avatar.js";
import { listIdentityUsage } from "../../identity-usage.js";
import { normalizeIdentityIcon } from "../../room-avatar.js";
import {
  defaultIdentityNameForRuntime,
  isAutoGeneratedIdentityName,
  listCanonicalRuntimeProfiles,
  listRuntimeModels,
  resolveCanonicalRuntimeProfile,
  runtimeOptionLabel,
} from "../../runtime.js";
import { RoomAvatarUploadButton } from "../ui/RoomAvatarUploadButton.js";
import { ToastTip } from "../ui/ToastTip.js";
import { IdentityUsagePanel } from "./IdentityUsagePanel.js";

export function IdentityEditor(props: {
  identity: Identity;
  inUseCount: number;
  participants: Participant[];
  conversations: Conversation[];
  rooms: Room[];
  runtimeProfiles: RuntimeProfile[];
  localAgentProviders: LocalAgentProviderStatus[];
  isNew?: boolean;
  embedded?: boolean;
  onClose?: () => void;
  onOpenConversation?: (conversationId: string) => void;
  onSave: (updates: CreateIdentityRequest) => Promise<{ identity: Identity | null } | void>;
  onDelete?: () => void | Promise<void>;
  deleting?: boolean;
}) {
  const [name, setName] = useState(props.identity.name);
  const [icon, setIcon] = useState(props.identity.icon);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [roleDescription, setRoleDescription] = useState(
    () => normalizeRoleDescriptionForEditor(props.identity),
  );
  const [selectedRolePresetId, setSelectedRolePresetId] = useState(
    () => matchRolePresetId(normalizeRoleDescriptionForEditor(props.identity)),
  );
  const [runtimeProfileId, setRuntimeProfileId] = useState(props.identity.defaultRuntimeProfileId ?? "");
  const [model, setModel] = useState("");
  const [reasoningEffort, setReasoningEffort] = useState<"" | ReasoningEffort>(
    props.identity.defaultReasoningEffort ?? "",
  );
  const [saving, setSaving] = useState(false);
  const [saveTip, setSaveTip] = useState<string | null>(null);
  const [confirmDeleteOpen, setConfirmDeleteOpen] = useState(false);
  const saveTipTimerRef = useRef<number | null>(null);
  const syncedIdentityRevisionRef = useRef("");
  const syncedIdentityIdRef = useRef(props.identity.id);
  const nameTouchedRef = useRef(!props.isNew && !isAutoGeneratedIdentityName(props.identity.name));

  const syncFromIdentity = (identity: Identity) => {
    const nextRoleDescription = normalizeRoleDescriptionForEditor(identity);
    setName(identity.name);
    setIcon(identity.icon);
    setUploadError(null);
    setRoleDescription(nextRoleDescription);
    setSelectedRolePresetId(matchRolePresetId(nextRoleDescription));
    setRuntimeProfileId(identity.defaultRuntimeProfileId ?? "");
    setReasoningEffort(identity.defaultReasoningEffort ?? "");
    const runtime =
      props.runtimeProfiles.find((profile) => profile.id === identity.defaultRuntimeProfileId) ?? null;
    setModel(runtime?.model ?? "");
    setConfirmDeleteOpen(false);
    nameTouchedRef.current = !props.isNew && !isAutoGeneratedIdentityName(identity.name);
    syncedIdentityRevisionRef.current = `${identity.id}:${identity.updatedAt}`;
    syncedIdentityIdRef.current = identity.id;
  };

  const runtimeOptions = useMemo(
    () => listCanonicalRuntimeProfiles(props.runtimeProfiles),
    [props.runtimeProfiles],
  );
  const selectedRuntime =
    props.runtimeProfiles.find((profile) => profile.id === runtimeProfileId) ??
    props.runtimeProfiles.find((profile) => profile.id === props.identity.defaultRuntimeProfileId) ??
    null;
  const canonicalRuntime = resolveCanonicalRuntimeProfile(selectedRuntime, props.runtimeProfiles);
  const modelOptions = listRuntimeModels(selectedRuntime, props.localAgentProviders);
  const identityUsage = useMemo(
    () => listIdentityUsage(props.identity, props.participants, props.conversations, props.rooms),
    [props.conversations, props.identity, props.participants, props.rooms],
  );
  const headerAvatar = useMemo(
    () => resolveAgentAvatar({ icon, avatar: icon, runtimeProfile: selectedRuntime }),
    [icon, selectedRuntime],
  );

  useEffect(() => {
    const identityRevision = `${props.identity.id}:${props.identity.updatedAt}`;
    const identityChanged = syncedIdentityIdRef.current !== props.identity.id;
    if (identityChanged || syncedIdentityRevisionRef.current !== identityRevision) {
      syncFromIdentity(props.identity);
    }
  }, [props.identity]);

  useEffect(() => {
    const runtime =
      props.runtimeProfiles.find((profile) => profile.id === runtimeProfileId) ??
      props.runtimeProfiles.find((profile) => profile.id === props.identity.defaultRuntimeProfileId) ??
      null;
    if (runtime?.model) setModel(runtime.model);
  }, [props.identity.defaultRuntimeProfileId, props.runtimeProfiles, runtimeProfileId]);

  useEffect(() => {
    if (!props.isNew || nameTouchedRef.current) return;
    const runtime =
      props.runtimeProfiles.find((profile) => profile.id === runtimeProfileId) ??
      props.runtimeProfiles.find((profile) => profile.id === props.identity.defaultRuntimeProfileId) ??
      null;
    const canonical = resolveCanonicalRuntimeProfile(runtime, props.runtimeProfiles);
    const nextName = defaultIdentityNameForRuntime(canonical, props.localAgentProviders);
    if (nextName !== name) setName(nextName);
  }, [name, props.identity.defaultRuntimeProfileId, props.isNew, props.localAgentProviders, props.runtimeProfiles, runtimeProfileId]);

  useEffect(() => () => {
    if (saveTipTimerRef.current) window.clearTimeout(saveTipTimerRef.current);
  }, []);

  const showSaveTip = (message: string) => {
    setSaveTip(message);
    if (saveTipTimerRef.current) window.clearTimeout(saveTipTimerRef.current);
    saveTipTimerRef.current = window.setTimeout(() => {
      setSaveTip(null);
      saveTipTimerRef.current = null;
    }, 2000);
  };

  const save = async () => {
    setSaving(true);
    try {
      const result = await props.onSave({
        name,
        icon: normalizeIdentityIcon(icon),
        systemPrompt: roleDescription,
        stylePrompt: "",
        defaultRuntimeProfileId: runtimeProfileId || null,
        defaultListenMode: DEFAULT_PARTICIPANT_LISTEN_MODE,
        defaultReasoningEffort: reasoningEffort || null,
        model: model || undefined,
      });
      const savedIdentity = result?.identity ?? null;
      if (!savedIdentity) {
        throw new Error("保存失败，请重试");
      }
      syncFromIdentity(savedIdentity);
      showSaveTip(props.isNew ? "创建成功" : "保存成功");
    } catch (error) {
      window.alert(error instanceof Error ? error.message : "保存失败");
    } finally {
      setSaving(false);
    }
  };

  const embedded = props.embedded ?? false;
  const fieldLabel = "[color:#525252] [font-size:12px] [font-weight:650] [line-height:1.35]";
  const fieldControl =
    "[height:42px] [min-width:0] [border:1px_solid_var(--border)] [border-radius:12px] [padding:0_12px] [color:var(--text)] [background:var(--panel)] [font-size:13px] [outline:none] focus:[border-color:var(--border-strong)] focus:[box-shadow:0_0_0_3px_#00000008]";
  const selectControl = `${fieldControl} [appearance:none] [padding:0_42px_0_12px] [background-color:var(--panel)] [background-image:var(--select-chevron)] [background-repeat:no-repeat] [background-position:right_14px_center] [background-size:16px_16px]`;
  const sectionLayout = "[display:grid] [gap:10px]";

  return (
    <div
      className={
        embedded
          ? "[display:grid] [height:100%] [min-height:0] [grid-template-rows:auto_minmax(0,_1fr)_auto] [overflow:hidden] [background:var(--panel)]"
          : "[background:var(--panel)] [display:grid] [grid-template-rows:76px_minmax(0,_1fr)_auto] [width:min(1060px,_calc(100vw_-_200px))] [height:min(860px,_calc(100vh_-_84px))] [overflow:hidden] [border:1px_solid_#00000014] [border-radius:30px] [box-shadow:0_18px_60px_rgb(0_0_0_/_22%)]"
      }
    >
      <div className={"[display:flex] [flex:0_0_auto] [align-items:center] [justify-content:space-between] [gap:16px] [padding:14px_20px] [border-bottom:1px_solid_var(--border)]"}>
        <div className={"[display:flex] [min-width:0] [align-items:center] [gap:10px] [&_h2]:[margin:0] [&_h2]:[overflow:hidden] [&_h2]:[color:var(--text)] [&_h2]:[font-size:17px] [&_h2]:[font-weight:700] [&_h2]:[line-height:1.2] [&_h2]:[text-overflow:ellipsis] [&_h2]:[white-space:nowrap]"}>
          <RoomAvatarUploadButton
            title={name || props.identity.name}
            avatar={headerAvatar.avatar}
            provider={headerAvatar.provider}
            size={40}
            agent
            onUpload={(avatar) => {
              setIcon(avatar);
              setUploadError(null);
            }}
            onError={setUploadError}
          />
          <div className={"[min-width:0]"}>
            <h2>{name || "未命名 Agent"}</h2>
            <p className={"[margin:2px_0_0] [color:var(--muted)] [font-size:12px] [line-height:1.35]"}>
              {props.isNew ? "新建 Agent 身份" : "Agent 身份配置"}
            </p>
            {uploadError ? (
              <p className={"[margin:4px_0_0] [color:var(--danger)] [font-size:11px] [line-height:1.35]"}>{uploadError}</p>
            ) : null}
          </div>
        </div>
        {props.onClose ? (
          <button className={"[display:inline-grid] [width:34px] [height:34px] [place-items:center] [border:0] [border-radius:999px] [color:var(--muted)] [background:transparent] [transition:background-color_0.12s_ease,_color_0.12s_ease] [&:hover]:[color:var(--text)] [&:hover]:[background:#0000000a]"} aria-label="关闭" title="关闭" onClick={props.onClose}>
            <X size={18} />
          </button>
        ) : null}
      </div>

      <div className={"[display:grid] [min-height:0] [grid-template-columns:minmax(0,_1fr)]"}>
        <div className={`[min-width:0] [overflow:auto] ${embedded ? "[padding:18px_20px_16px]" : "[padding:24px_32px_20px]"}`}>
          <div className={"[display:grid] [gap:24px] [width:100%]"}>
            {!props.isNew ? (
              <section className={sectionLayout}>
                <h3 className={"[margin:0] [color:var(--text)] [font-size:15px] [font-weight:720]"}>使用情况</h3>
                <IdentityUsagePanel
                  usage={identityUsage}
                  identityIcon={props.identity.icon}
                  identityProvider={selectedRuntime?.provider ?? null}
                  onOpenConversation={props.onOpenConversation}
                />
              </section>
            ) : null}

            <section className={sectionLayout}>
              <h3 className={"[margin:0] [color:var(--text)] [font-size:15px] [font-weight:720]"}>基础信息</h3>
              <label className={"[display:flex] [align-items:center] [gap:12px] max-[760px]:[flex-direction:column] max-[760px]:[align-items:stretch]"}>
                <span className={`${fieldLabel} [flex-shrink:0] [width:48px]`}>名称</span>
                <input
                  aria-label="Name"
                  className={`${fieldControl} [flex:1_1_auto] [min-width:0]`}
                  value={name}
                  onChange={(event) => {
                    nameTouchedRef.current = true;
                    setName(event.target.value);
                  }}
                />
              </label>
            </section>

            <section className={sectionLayout}>
              <h3 className={"[margin:0] [color:var(--text)] [font-size:15px] [font-weight:720]"}>运行时</h3>
              <div className={"[display:grid] [grid-template-columns:repeat(3,_minmax(0,_1fr))] [gap:16px] max-[760px]:[grid-template-columns:1fr]"}>
                <label className={"[display:grid] [gap:8px]"}>
                  <span className={fieldLabel}>运行时</span>
                  <select
                    aria-label="Runtime"
                    className={selectControl}
                    value={canonicalRuntime?.id ?? runtimeProfileId}
                    onChange={(event) => {
                      const nextProfile = props.runtimeProfiles.find((profile) => profile.id === event.target.value) ?? null;
                      const nextCanonical = resolveCanonicalRuntimeProfile(nextProfile, props.runtimeProfiles);
                      setRuntimeProfileId(event.target.value);
                      setModel(nextProfile?.model ?? "");
                      if (props.isNew && !nameTouchedRef.current) {
                        setName(defaultIdentityNameForRuntime(nextCanonical, props.localAgentProviders));
                      }
                    }}
                  >
                    {runtimeOptions.map((profile) => (
                      <option key={profile.id} value={profile.id}>
                        {runtimeOptionLabel(profile, props.localAgentProviders)}
                      </option>
                    ))}
                  </select>
                </label>
                <label className={"[display:grid] [gap:8px]"}>
                  <span className={fieldLabel}>模型</span>
                  {modelOptions.length ? (
                    <select aria-label="Model" className={selectControl} value={model} onChange={(event) => setModel(event.target.value)}>
                      {modelOptions.map((option) => (
                        <option key={option.id} value={option.id}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                  ) : (
                    <input value={model || "未配置"} readOnly aria-readonly className={`${fieldControl} [color:var(--muted)] [background:#f3f4f6] [cursor:default]`} />
                  )}
                </label>
                <label className={"[display:grid] [gap:8px]"}>
                  <span className={fieldLabel}>{reasoningModeFieldLabel(reasoningEffort)}</span>
                  <select
                    aria-label="Reasoning mode"
                    className={selectControl}
                    value={reasoningEffort}
                    onChange={(event) => setReasoningEffort(event.target.value as "" | ReasoningEffort)}
                  >
                    {reasoningEffortOptions.map((option) => (
                      <option key={option.value || "auto"} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                </label>
              </div>
            </section>

            <section className={sectionLayout}>
              <h3 className={"[margin:0] [color:var(--text)] [font-size:15px] [font-weight:720]"}>角色设定</h3>
              <div className={"[display:flex] [flex-wrap:wrap] [gap:8px]"}>
                {roleDescriptionPresets.map((preset) => {
                  const selected = selectedRolePresetId === preset.id;
                  return (
                    <button
                      key={preset.id}
                      type="button"
                      aria-pressed={selected}
                      className={`[border:1px_solid_var(--border)] [border-radius:999px] [padding:6px_12px] [color:#525252] [background:#f7f7f8] [font-size:12px] [font-weight:650] [transition:background-color_0.12s_ease,_border-color_0.12s_ease,_color_0.12s_ease] [&:hover]:[border-color:#17171733] [&:hover]:[color:var(--text)] ${selected ? "![border-color:#171717] ![color:#ffffff] ![background:#171717]" : ""}`}
                      onClick={() => {
                        setSelectedRolePresetId(preset.id);
                        setRoleDescription(preset.description);
                      }}
                    >
                      {preset.name}
                    </button>
                  );
                })}
              </div>
              <textarea
                aria-label="Role Description"
                className={"[min-width:0] [min-height:168px] [border:1px_solid_var(--border)] [border-radius:14px] [padding:14px] [color:var(--text)] [background:var(--panel)] [font-size:13px] [line-height:1.6] [outline:none] [resize:vertical] focus:[border-color:var(--border-strong)] focus:[box-shadow:0_0_0_3px_#00000008]"}
                value={roleDescription}
                onChange={(event) => {
                  const nextValue = event.target.value;
                  setSelectedRolePresetId(matchRolePresetId(nextValue));
                  setRoleDescription(nextValue);
                }}
              />
            </section>
          </div>
        </div>
      </div>

      <div className={"[display:flex] [flex:0_0_auto] [flex-wrap:wrap] [align-items:center] [justify-content:space-between] [gap:10px] [padding:14px_20px] [border-top:1px_solid_var(--border)] [background:var(--panel)]"}>
        {!props.isNew && props.onDelete ? (
          <button
            type="button"
            className={"[display:inline-flex] [align-items:center] [gap:5px] [border:0] [border-radius:12px] [font-size:13px] [font-weight:650] [height:40px] [padding:0_16px] [color:var(--danger)] [background:#fde8e7] [&:disabled]:[opacity:0.5]"}
            disabled={props.deleting}
            onClick={() => setConfirmDeleteOpen(true)}
          >
            <Trash2 size={14} />
            {props.deleting ? "删除中..." : "删除 Agent"}
          </button>
        ) : (
          <span />
        )}
        <button
          className={"[display:inline-flex] [align-items:center] [justify-content:center] [gap:6px] [border:0] [border-radius:12px] [font-size:13px] [font-weight:650] [height:40px] [padding:0_18px] [color:var(--primary-contrast)] [background:var(--primary)] [&:disabled]:[opacity:0.5]"}
          aria-label="Save"
          onClick={save}
          disabled={saving || props.deleting}
        >
          {saving ? "保存中..." : props.isNew ? "创建" : "保存"}
        </button>
      </div>

      {confirmDeleteOpen && props.onDelete ? (
        <div
          className={"[position:fixed] [inset:0] [z-index:80] [display:grid] [place-items:center] [padding:24px] [background:rgb(15_23_42_/_52%)]"}
          role="presentation"
          onPointerDown={(event) => {
            if (event.target === event.currentTarget && !props.deleting) setConfirmDeleteOpen(false);
          }}
        >
          <div
            role="alertdialog"
            aria-modal="true"
            aria-labelledby="identity-delete-title"
            aria-describedby="identity-delete-desc"
            className={"[width:min(420px,_calc(100vw_-_32px))] [overflow:hidden] [border:1px_solid_var(--border)] [border-radius:18px] [background:var(--panel)] [box-shadow:0_24px_80px_rgb(0_0_0_/_24%)]"}
            onPointerDown={(event) => event.stopPropagation()}
          >
            <div className={"[padding:20px_20px_16px]"}>
              <h3 id="identity-delete-title" className={"[margin:0] [color:var(--text)] [font-size:16px] [font-weight:720] [line-height:1.35]"}>
                删除 Agent「{name || props.identity.name}」？
              </h3>
              <p id="identity-delete-desc" className={"[margin:10px_0_0] [color:var(--muted)] [font-size:13px] [line-height:1.55]"}>
                {props.inUseCount > 0 ? (
                  <>
                    该 Agent 当前在 <strong className={"[color:var(--text)] [font-weight:720]"}>{props.inUseCount}</strong> 个房间中使用。
                    删除后将从这些房间移除，历史消息会保留。
                  </>
                ) : (
                  "该 Agent 尚未加入任何房间。删除后无法恢复，请确认。"
                )}
              </p>
            </div>
            <div className={"[display:flex] [justify-content:flex-end] [gap:8px] [padding:0_20px_20px]"}>
              <button
                type="button"
                className={"[display:inline-flex] [height:36px] [align-items:center] [border:1px_solid_var(--border)] [border-radius:10px] [padding:0_14px] [color:var(--text)] [background:var(--panel)] [font-size:13px] [font-weight:650] [&:disabled]:[opacity:0.5]"}
                disabled={props.deleting}
                onClick={() => setConfirmDeleteOpen(false)}
              >
                取消
              </button>
              <button
                type="button"
                className={"[display:inline-flex] [height:36px] [align-items:center] [border:0] [border-radius:10px] [padding:0_14px] [color:#ffffff] [background:var(--danger)] [font-size:13px] [font-weight:650] [&:disabled]:[opacity:0.5]"}
                disabled={props.deleting}
                onClick={() => {
                  void Promise.resolve(props.onDelete!()).finally(() => setConfirmDeleteOpen(false));
                }}
              >
                {props.deleting ? "删除中..." : "确认删除"}
              </button>
            </div>
          </div>
        </div>
      ) : null}
      <ToastTip message={saveTip} />
    </div>
  );
}

function matchRolePresetId(description: string) {
  const normalized = description.trim();
  if (!normalized) return "custom";
  const matched = roleDescriptionPresets.find(
    (preset) => preset.id !== "custom" && preset.description.trim() === normalized,
  );
  return matched?.id ?? null;
}

function normalizeRoleDescriptionForEditor(identity: Identity) {
  const description = getIdentityRoleDescription(identity);
  if (description === defaultRoleDescription) return "";
  return description;
}
