import { Info, RefreshCw, Terminal } from "lucide-react";
import type { LocalAgentProviderSpeedMode, LocalAgentProviderStatus, ReasoningEffort, RuntimeProfile } from "@group-chat/shared";
import { t, useTranslation } from "./i18n/index.js";

const DEFAULT_LOCAL_AGENT_MODEL_ID = "default";

export function defaultIdentityNameForRuntime(
  profile: RuntimeProfile | null,
  localAgentProviders: LocalAgentProviderStatus[] = [],
) {
  if (!profile) return "Agent";
  const provider = profile.provider.trim().toLowerCase();
  if (provider === "codex") return "Codex";
  if (provider === "claude") return "Claude Code";
  const detected = localAgentStatus(profile, localAgentProviders);
  if (detected?.displayName?.trim()) return detected.displayName.trim();
  return profile.displayName.replace(/\s+Local Agent$/i, "").trim() || profile.displayName;
}

export function isAutoGeneratedIdentityName(name: string) {
  return /^本地 Agent \d+$/.test(name.trim());
}

export function preferredDefaultRuntimeProfile(profiles: RuntimeProfile[]) {
  return (
    profiles.find((profile) => profile.id === "local-agent:codex")
    ?? profiles.find((profile) => profile.kind === "local-agent")
    ?? profiles[0]
    ?? null
  );
}

export function runtimeOptionLabel(profile: RuntimeProfile, localAgentProviders: LocalAgentProviderStatus[]) {
  const status = localAgentStatus(profile, localAgentProviders);
  if (!status) return t("runtime.optionDetecting", { name: profile.displayName });
  return status.available
    ? t("runtime.optionReady", { name: profile.displayName })
    : t("runtime.optionUnready", { name: profile.displayName });
}

export function runtimeStatusSummary(profile: RuntimeProfile | null, localAgentProviders: LocalAgentProviderStatus[]) {
  if (!profile) return t("runtime.noRuntime");
  if (profile.kind !== "local-agent") return t("runtime.serverRuntime");
  const status = localAgentStatus(profile, localAgentProviders);
  if (!status) return t("runtime.detecting");
  return status.available ? t("runtime.ready") : t("runtime.needsSetup");
}

export function localAgentStatus(profile: RuntimeProfile | null, localAgentProviders: LocalAgentProviderStatus[]) {
  if (!profile || profile.kind !== "local-agent") return null;
  return localAgentProviders.find((item) => item.provider === profile.provider) ?? null;
}

export function listRuntimeModels(
  profile: RuntimeProfile | null,
  localAgentProviders: LocalAgentProviderStatus[],
) {
  if (!profile) return [];
  const rawDetected = localAgentStatus(profile, localAgentProviders)?.models ?? [];
  const detected = rawDetected.length > 1
    ? rawDetected.filter((model) => !isDefaultModelOptionId(model.id))
    : rawDetected;
  if (detected.length) {
    const normalizedProfileModel = normalizeRuntimeModelId(profile, profile.model);
    if (isDefaultLocalAgentModelId(profile, profile.model)) return detected;
    if (!normalizedProfileModel || detected.some((model) => model.id === normalizedProfileModel)) return detected;
    return [{ id: normalizedProfileModel, label: normalizedProfileModel }, ...detected];
  }
  const normalizedProfileModel = normalizeRuntimeModelId(profile, profile.model);
  if (normalizedProfileModel) {
    return [{
      id: normalizedProfileModel,
      label: isDefaultLocalAgentModelId(profile, profile.model)
        ? t("runtime.defaultCliModel")
        : normalizedProfileModel,
    }];
  }
  return [];
}

export function preferredRuntimeModelId(
  profile: RuntimeProfile | null,
  localAgentProviders: LocalAgentProviderStatus[],
) {
  const options = listRuntimeModels(profile, localAgentProviders);
  const provider = localAgentStatus(profile, localAgentProviders);
  const preferred = normalizeRuntimeModelId(profile, provider?.defaultModelId ?? profile?.model ?? "");
  if (preferred && options.some((option) => option.id === preferred)) return preferred;
  return options[0]?.id ?? "";
}

export function resolveRuntimeModelId(
  profile: RuntimeProfile | null,
  localAgentProviders: LocalAgentProviderStatus[],
  modelId: string | null | undefined,
) {
  const options = listRuntimeModels(profile, localAgentProviders);
  const normalized = normalizeRuntimeModelId(profile, modelId);
  if (normalized && options.some((option) => option.id === normalized)) return normalized;
  return preferredRuntimeModelId(profile, localAgentProviders);
}

export function normalizeRuntimeModelId(profile: RuntimeProfile | null, modelId: string | null | undefined) {
  const trimmed = modelId?.trim() ?? "";
  if (!trimmed) return "";
  return isDefaultLocalAgentModelId(profile, trimmed) ? DEFAULT_LOCAL_AGENT_MODEL_ID : trimmed;
}

function isDefaultLocalAgentModelId(profile: RuntimeProfile | null, modelId: string | null | undefined) {
  if (!profile || profile.kind !== "local-agent") return false;
  return modelId === `${profile.provider}:default`;
}

function isDefaultModelOptionId(modelId: string | null | undefined) {
  return modelId?.trim().toLowerCase() === DEFAULT_LOCAL_AGENT_MODEL_ID;
}

export function listRuntimeReasoningOptions(
  profile: RuntimeProfile | null,
  localAgentProviders: LocalAgentProviderStatus[],
  modelId: string,
  allOptions: Array<{ value: "" | ReasoningEffort; label: string; description: string }>,
) {
  const provider = localAgentStatus(profile, localAgentProviders);
  const model = provider?.models.find((item) => item.id === modelId);
  const supported = model?.supportedReasoningEfforts ?? provider?.reasoningEfforts;
  if (!supported?.length) {
    return profile?.kind === "local-agent"
      ? allOptions.filter((option) => option.value)
      : allOptions;
  }
  const allowed = new Set<ReasoningEffort>(supported);
  const filtered = allOptions.filter((option) => option.value && allowed.has(option.value));
  return filtered.length ? filtered : allOptions;
}

export function listRuntimeSpeedOptions(
  profile: RuntimeProfile | null,
  localAgentProviders: LocalAgentProviderStatus[],
): LocalAgentProviderSpeedMode[] {
  const provider = localAgentStatus(profile, localAgentProviders);
  if (provider?.speedModes?.length) return provider.speedModes;
  if (profile?.kind === "local-agent" && profile.provider === "codex") {
    return [
      { id: "standard", label: t("speed.standard") },
      { id: "fast", label: t("speed.fast") },
    ];
  }
  return [{ id: "standard", label: t("speed.standard") }];
}

export function resolveRuntimeSpeedMode(
  profile: RuntimeProfile | null,
  localAgentProviders: LocalAgentProviderStatus[],
  speedMode: string | null | undefined,
) {
  const options = listRuntimeSpeedOptions(profile, localAgentProviders);
  if (speedMode && options.some((option) => option.id === speedMode)) return speedMode;
  const providerDefault = localAgentStatus(profile, localAgentProviders)?.defaultSpeedMode;
  if (providerDefault && options.some((option) => option.id === providerDefault)) return providerDefault;
  return options[0]?.id ?? "standard";
}

function isCanonicalLocalAgentProfile(profile: RuntimeProfile) {
  return profile.kind === "local-agent" && profile.id === `local-agent:${profile.provider}`;
}

export function listCanonicalRuntimeProfiles(profiles: RuntimeProfile[]) {
  return profiles.filter((profile) => profile.kind !== "local-agent" || isCanonicalLocalAgentProfile(profile));
}

export function resolveCanonicalRuntimeProfile(profile: RuntimeProfile | null, profiles: RuntimeProfile[]) {
  if (!profile) return null;
  if (isCanonicalLocalAgentProfile(profile)) return profile;
  return (
    profiles.find(
      (item) =>
        item.kind === "local-agent" &&
        item.provider === profile.provider &&
        isCanonicalLocalAgentProfile(item),
    ) ?? profile
  );
}

export function RuntimeStatusHint(props: {
  profile: RuntimeProfile | null;
  localAgentProviders: LocalAgentProviderStatus[];
}) {
  const { t } = useTranslation();
  if (!props.profile) {
    return <span className={"[display:block] [min-width:0] [overflow:hidden] [color:var(--text-secondary)] [font-size:11px] [font-weight:600] [line-height:1.35] [text-overflow:ellipsis] [white-space:nowrap] [color:var(--state-danger)]"}>{t("runtime.noRuntimeSelected")}</span>;
  }
  if (props.profile.kind !== "local-agent") {
    return <span className={"[display:block] [min-width:0] [overflow:hidden] [color:var(--text-secondary)] [font-size:11px] [font-weight:600] [line-height:1.35] [text-overflow:ellipsis] [white-space:nowrap]"}>{t("runtime.serverHosted")}</span>;
  }
  const status = localAgentStatus(props.profile, props.localAgentProviders);
  if (!status) {
    return <span className={"[display:block] [min-width:0] [overflow:hidden] [color:var(--text-secondary)] [font-size:11px] [font-weight:600] [line-height:1.35] [text-overflow:ellipsis] [white-space:nowrap]"}>{t("runtime.detectingProvider")}</span>;
  }
  if (!status.available) {
    return <span className={"[display:block] [min-width:0] [overflow:hidden] [color:var(--text-secondary)] [font-size:11px] [font-weight:600] [line-height:1.35] [text-overflow:ellipsis] [white-space:nowrap] [color:var(--state-danger)]"}>{t("runtime.needsSetup")} · {status.reason ?? t("runtime.providerUnavailable")}</span>;
  }
  const version = status.version && status.version !== "not-installed" ? status.version : null;
  return <span className={"[display:block] [min-width:0] [overflow:hidden] [color:var(--text-secondary)] [font-size:11px] [font-weight:600] [line-height:1.35] [text-overflow:ellipsis] [white-space:nowrap] [color:var(--state-success)]"}>{t("runtime.ready")}{version ? ` · ${version}` : ""}</span>;
}

function providerStatusLine(profile: RuntimeProfile, status: LocalAgentProviderStatus | null) {
  if (!status) return `${profile.provider} · ${t("runtime.detecting")}`;
  const modelCount = status.models.length;
  const modelLabel = modelCount === 1
    ? t("runtime.modelCountOne")
    : t("runtime.modelCountMany", { count: modelCount });
  return status.available
    ? `${t("runtime.ready")} · ${status.version} · ${modelLabel}`
    : `${t("runtime.needsSetup")} · ${status.reason ?? t("runtime.unavailable")}`;
}

function providerDetailLine(status: LocalAgentProviderStatus | null) {
  if (!status) return t("runtime.waitingDetection");
  if (!status.available) return status.reason ?? t("runtime.unavailable");
  return status.executablePath || status.configDir || t("runtime.available");
}

function uniqueBy<TItem, TKey>(items: TItem[], getKey: (item: TItem) => TKey) {
  const seen = new Set<TKey>();
  return items.filter((item) => {
    const key = getKey(item);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function LocalAgentProvidersPanel(props: {
  runtimeProfiles: RuntimeProfile[];
  localAgentProviders: LocalAgentProviderStatus[];
  refreshing: boolean;
  onRefresh: () => Promise<void>;
}) {
  const { t } = useTranslation();
  const localProfiles = props.runtimeProfiles.filter((profile) => profile.kind === "local-agent");
  const providers = uniqueBy(
    localProfiles.map((profile) => ({
      profile,
      status: localAgentStatus(profile, props.localAgentProviders),
    })),
    (item) => item.profile.provider,
  );
  return (
    <section className={"[margin:8px] [overflow:hidden] [border:0] [border-top:1px_solid_var(--border-1)] [border-radius:0] [background:transparent]"} aria-label={t("runtime.localProviders")}>
      <div className={"[&_h3]:[margin:0] [&_h3]:[color:var(--text-primary)] [&_h3]:[font-size:13px] [&_h3]:[font-weight:650] [&_span]:[display:block] [&_span]:[margin-top:3px] [display:flex] [align-items:center] [justify-content:space-between] [gap:10px] [padding:12px] [border-bottom:0] [&_span]:[color:var(--text-secondary)] [&_span]:[font-size:11px]"}>
        <div>
          <h3>{t("runtime.localProviders")}</h3>
          <span>{t("runtime.configuredCount", { count: providers.length })}</span>
        </div>
        <button
          type="button"
          className={"[display:inline-grid] [place-items:center] [border:0] [width:34px] [height:34px] [border-radius:12px] [color:var(--text-secondary)] [background:var(--transparency-hover)] [transition:background-color_0.12s_ease,_color_0.12s_ease] [&:hover]:[color:var(--text-primary)] [&:hover]:[background:var(--line-focus-window)] [width:28px] [height:28px] [&:disabled]:[opacity:0.45]"}
          title={t("runtime.refreshProviders")}
          aria-label={t("runtime.refreshProviders")}
          disabled={props.refreshing}
          onClick={() => void props.onRefresh()}
        >
          <RefreshCw size={14} className={props.refreshing ? "[animation:spin_0.9s_linear_infinite]" : ""} />
        </button>
      </div>
      <div className={"[display:grid] [gap:4px] [padding:8px]"}>
        {providers.map(({ profile, status }) => (
          <div key={profile.provider} className={`[&_strong]:[display:block] [&_strong]:[min-width:0] [&_strong]:[overflow:hidden] [&_strong]:[text-overflow:ellipsis] [&_strong]:[white-space:nowrap] [&_span]:[display:block] [&_span]:[min-width:0] [&_span]:[overflow:hidden] [&_span]:[text-overflow:ellipsis] [&_span]:[white-space:nowrap] [&_small]:[display:block] [&_small]:[min-width:0] [&_small]:[overflow:hidden] [&_small]:[text-overflow:ellipsis] [&_small]:[white-space:nowrap] [&_small]:[color:var(--text-secondary)] [&_small]:[font-size:11px] [&_small]:[font-size:11px] [display:grid] [grid-template-columns:22px_minmax(0,_1fr)] [gap:8px] [align-items:start] [border-radius:12px] [padding:9px] [color:var(--text-secondary)] [background:transparent] [&_strong]:[color:var(--text-primary)] [&_strong]:[font-size:11px] [&_span]:[margin-top:2px] [&_span]:[font-size:11px] [&_span]:[font-weight:650] ${status?.available ? "[color:var(--state-success)]" : "[color:var(--state-danger)]"}`}>
            <Terminal size={15} />
            <div>
              <strong>{defaultIdentityNameForRuntime(profile, props.localAgentProviders)}</strong>
              <span>{providerStatusLine(profile, status)}</span>
              <small title={status?.executablePath || undefined}>{providerDetailLine(status)}</small>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
